sudo: false

dist: bionic

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - wget http://ftp.gnu.org/gnu/bison/bison-3.3.2.tar.gz
  - tar -zxvf bison-3.3.2.tar.gz
  - cd bison-3.3.2
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake .. -DAST_TESTS=1
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
